### ISSUE TITLE
PdfWriter TypeError with Compression=True under Python 3.x

### ISSUE THREAD

**Issue by troyhoffman** [pmaupin/pdfrw#91]
If you instantiate PdfWriter with compress=True under Python 3.x, it throws a TypeError exception in line 23 in compress.py when trying to compress an object. The problem is that the 3.x  version of zlib.compress() expects a byte array instead of a string. The fix is to encode the string before sending to zlib.compress().

I have a fix. It's conditional on the Python version and I've tested it under 2.7.8 and 3.6.1.  I'm just not 100% sure if the way I'm doing the conditional checking is consistent with the rest of the library. If you want, I can create a pull request.

**Comment by pmaupin** [comment]
That certainly was a problem.  Are you running the lastest master?  I thought I fixed it [here](https://github.com/pmaupin/pdfrw/commit/64e4b93ee2a948fe210c93187d3dce29ecfa0dc7).

If that doesn't work for you, I'd certainly like to know what you need; a small patch dropped in the issue here would be just fine.

Thanks,
Pat

**Comment by troyhoffman** [comment]
I'm not running the latest master apparently, just latest release (0.3). Oops! I'm heading home for the day, but I'll update tomorrow and try again. I had a few other minor issues, but I'll make sure they're not fixed in master before entering any more.

I did something similar, but yours is a bit more elegant.

**Comment by troyhoffman** [comment]
It looks like your release from yesterday isn't up on PyPI, but I installed manually and it fixed the problem (and in a more elegant way than I had). I had to tweak the version on my local copy so I could make sure I had the latest code (it's still 0.3 which is the same version as the October release).

**Comment by pmaupin** [comment]
Yeah, we need a new release soon.  I wanted to get more stuff in it, but perhaps a bug-fix release to 0.4 without some of the new stuff first.

**Comment by troyhoffman** [comment]
Since this is fixed in master, closing this as a duplicate.
